name: Example of using the Korbit AI mentor manually
on:
  workflow_dispatch:
    inputs:
      path:
        description: "Path to scan"
        default: "example"
        required: true
jobs:
  scan-code:
    name: An example of using the Korbit AI mentor github action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Scan path
        uses: korbit-ai/korbit-mentor-action@v1
        id: check
        with:
          path: ${{ github.event.inputs.path }}
          threshold_confidence: 10
          threshold_priority: 10
          headless: false
          secret_id: ${{ secrets.KORBIT_SECRET_ID }}
          secret_key: ${{ secrets.KORBIT_SECRET_KEY }}